module.exports = function () {
  var data = {
    gyms: [
      {
        id: 1,
        nameGym: "Smart Fit",
        codeGym: "SMARTFIT",
        rucGym: "20600597940",
        rsGym: "SMARTFIT PERU S.A.C.",
      },
      {
        id: 2,
        nameGym: "Galaxy Fitness",
        codeGym: "GALAXY",
        rucGym: "20102029811",
        rsGym: "FITNESS S.A.C.",
      },
      {
        id: 3,
        nameGym: "Gimnasio B2",
        codeGym: "GYMB2",
        rucGym: "20604750530",
        rsGym: "GYM TRECE S.A.C.",
      },
      {
        id: 4,
        nameGym: "Gym Plus",
        codeGym: "GYMPLUS",
        rucGym: "20536570013",
        rsGym: "GYM PLUS S.A.C.",
      },
      {
        id: 5,
        nameGym: "BodyTech",
        codeGym: "BODYTECH",
        rucGym: "20492858766",
        rsGym: "INVERDESA PERU S.A.C.",
      },
      {
        id: 6,
        nameGym: "Sportlife Fitness Club",
        codeGym: "YTBGYM",
        rucGym: "20423621827",
        rsGym: "YTB FITNESS S.A.C.",
      },
      {
        id: 7,
        nameGym: "Gold Gym",
        codeGym: "GOLDGYM",
        rucGym: "20600307194",
        rsGym: "GOLD GYM S.A.C.",
      },
      {
        id: 8,
        nameGym: "X Sport Gym",
        codeGym: "XSPORT",
        rucGym: "20555032146",
        rsGym: "SPORT FITNESS PERU S.A.C",
      },
      {
        id: 9,
        nameGym: "Iron House Gym",
        codeGym: "IRONHOUSE",
        rucGym: "20581234571",
        rsGym: "IRON HOUSE S.A.C.",
      },
      {
        id: 10,
        nameGym: "Fit Stop",
        codeGym: "FITSTOP",
        rucGym: "20452467951",
        rsGym: "FIT STOP S.A.C.",
      },
      {
        id: 11,
        nameGym: "Flex Fitness",
        codeGym: "FLEXFIT",
        rucGym: "20569873691",
        rsGym: "FLEX FITNESS S.A.C.",
      },
      {
        id: 12,
        nameGym: "MegaSport Gym",
        codeGym: "MEGASPORT",
        rucGym: "20601234567",
        rsGym: "MEGASPORT S.A.C.",
      },
      {
        id: 13,
        nameGym: "Oxigeno Gym",
        codeGym: "OXIGENO",
        rucGym: "20156789012",
        rsGym: "OXIGENO FITNESS S.A.C.",
      },
      {
        id: 14,
        nameGym: "Gym Zone",
        codeGym: "GYMZONE",
        rucGym: "20234567891",
        rsGym: "GYM ZONE PERU S.A.C.",
      },
      {
        id: 15,
        nameGym: "Elite Fitness",
        codeGym: "ELITEFIT",
        rucGym: "20493847561",
        rsGym: "ELITE FITNESS S.A.C.",
      },
      {
        id: 16,
        nameGym: "Power House Gym",
        codeGym: "POWERHOUSE",
        rucGym: "20784562139",
        rsGym: "POWER HOUSE FITNESS S.A.C.",
      },
      {
        id: 17,
        nameGym: "Power Fitness",
        codeGym: "POWERFIT",
        rucGym: "20605794315",
        rsGym: "POWER FITNESS S.A.C.",
      },
      {
        id: 18,
        nameGym: "Iron Gym",
        codeGym: "IRONGYM",
        rucGym: "20591486985",
        rsGym: "IRON GYM PERU S.A.C.",
      },
      {
        id: 19,
        nameGym: "The Gym",
        codeGym: "THEGYM",
        rucGym: "20602046701",
        rsGym: "THE GYM PERU S.A.C.",
      },
      {
        id: 20,
        nameGym: "Fitness 24",
        codeGym: "FIT24",
        rucGym: "20601912547",
        rsGym: "FITNESS 24 S.A.C.",
      },
    ],
  };
  return data;
};

//"@angular/material/prebuilt-themes/indigo-pink.css", tema original en angular.json
